# Generated by Django 2.1.2 on 2018-11-27 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_client_extra_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncedAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whmcs_id', models.IntegerField()),
                ('whmcs_uuid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('subaccount', models.BooleanField(db_index=True, default=False)),
                ('password_synced', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='syncedaccount',
            unique_together={('whmcs_id', 'subaccount')},
        ),
    ]
