# Generated by Django 2.1.2 on 2018-11-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whmcsync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncedaccount',
            name='whmcs_uuid',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
