# Generated by Django 3.2.9 on 2021-12-08 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whmcsync', '0002_uuid_not_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncedaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='syncedaccount',
            unique_together=set(),
        ),
    ]
